# Generated by Django 3.1.1 on 2020-09-07 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cusid', models.CharField(db_column='cusId', max_length=8, primary_key=True, serialize=False)),
                ('cusnic', models.CharField(db_column='cusNIC', max_length=10)),
                ('f_name', models.CharField(blank=True, db_column='f_Name', max_length=10, null=True)),
                ('l_name', models.CharField(blank=True, db_column='l_Name', max_length=10, null=True)),
                ('address_l1', models.CharField(blank=True, db_column='address_L1', max_length=30, null=True)),
                ('address_l2', models.CharField(blank=True, db_column='address_L2', max_length=30, null=True)),
                ('postcode', models.IntegerField(blank=True, null=True)),
                ('img', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=150, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.CharField(db_column='empId', max_length=6, primary_key=True, serialize=False)),
                ('empnic', models.CharField(db_column='empNIC', max_length=10)),
                ('faceid', models.CharField(db_column='faceID', max_length=500)),
                ('f_name', models.CharField(blank=True, db_column='f_Name', max_length=10, null=True)),
                ('l_name', models.CharField(blank=True, db_column='l_Name', max_length=10, null=True)),
                ('address_l1', models.CharField(blank=True, db_column='address_L1', max_length=30, null=True)),
                ('address_l2', models.CharField(blank=True, db_column='address_L2', max_length=30, null=True)),
                ('postcode', models.IntegerField(blank=True, null=True)),
                ('img', models.CharField(blank=True, max_length=250, null=True)),
                ('basic_sal', models.FloatField(blank=True, db_column='basic_Sal', null=True)),
                ('ot_rate', models.FloatField(blank=True, db_column='OT_Rate', null=True)),
                ('reg_date', models.DateField(blank=True, db_column='reg_Date', null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'Employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.CharField(db_column='adminId', max_length=6, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('empid', models.ForeignKey(db_column='empId', on_delete=django.db.models.deletion.DO_NOTHING, to='userlogin.employee')),
            ],
            options={
                'db_table': 'admin',
                'managed': True,
                'unique_together': {('adminid', 'empid')},
            },
        ),
    ]
