# Generated by Django 3.1.1 on 2020-09-17 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_auto_20200913_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodItem',
            fields=[
                ('foodItemId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('dishName', models.CharField(max_length=100)),
                ('salesPrice', models.FloatField()),
                ('totalCost', models.FloatField()),
                ('costMargin', models.FloatField()),
                ('netProfit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='utilCost',
            fields=[
                ('utilId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('preparations', models.FloatField()),
                ('gas', models.FloatField()),
                ('elec', models.FloatField()),
                ('water', models.FloatField()),
                ('total', models.FloatField()),
                ('foodId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userlogin.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='ingrediants',
            fields=[
                ('ingId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ingName', models.CharField(max_length=50)),
                ('qty', models.FloatField()),
                ('cost', models.FloatField()),
                ('foodId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userlogin.fooditem')),
            ],
        ),
    ]
